[package]
name = "rnes"
version = "0.1.0"
edition = "2021"

[dependencies]
bitfield = "0.13.2"
clap = { version = "4.3.0", features = ["derive"] }
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros"] }
wgpu = "0.16.0"
winit = "0.28.6"

